[PRT-587] SDK todos after detailed review
lavanet/lava-sdk pull request #57
Opened 2023-05-03 07:24 UTC by Aleksao998

2023-05-07 17:02 UTC, ranlavanet requested changes

2023-05-07 17:02 UTC, ranlavanet commented on src/lavaOverLava/providers.ts
> +    console.log("Relay", relayCu);
woopsi :D

2023-05-08 07:58 UTC, Aleksao998 commented on src/lavaOverLava/providers.ts
> +    console.log("Relay", relayCu);
Fixed f2e3c5ae33c24a7d71fc13533b886725eacb3ce6

2023-05-08 15:06 UTC, ranlavanet approved these changes

2023-05-08 15:07 UTC, merged