PRT-623 remove supported json
lavanet/lava-sdk pull request #62
Opened 2023-05-06 18:00 UTC by Aleksao998

2023-05-07 17:35 UTC, ranlavanet requested changes

2023-05-07 17:35 UTC, ranlavanet commented on src/sdk/sdk.ts
> +      this.rpcInterface || fetchRpcInterface(this.chainID, parsedChainList);
we can validate if we need to fetch before, and if rpcInterface is specified we don't need to fetch

2023-05-07 17:35 UTC, ranlavanet commented on src/util/chains.ts
> +    if (chainInfo.chainID === chainID) {
Think we can use the "find" method here as well and return true if found? maybe its more efficient

2023-05-08 07:51 UTC, Aleksao998 commented on src/sdk/sdk.ts
> +      this.rpcInterface || fetchRpcInterface(this.chainID, parsedChainList);
If RPC is specified we will not fetch. 
for example:
```
const fetchRPCInterface=()=>{
  console.log("entered")
  return "rest"
}

var rpcInterfaceOption = "test"

const rpcInterface = rpcInterfaceOption ? rpcInterfaceOption:  fetchRPCInterface()

console.log(rpcInterface)
```

if rpcInterfaceOption is null, undefined or "" it is not entering in fetchRPCInterface

2023-05-08 08:15 UTC, Aleksao998 commented on src/util/chains.ts
> +    if (chainInfo.chainID === chainID) {
Fixed 1f1cd1f9b08ad3c89db866c039984357208c1e54

2023-05-08 12:21 UTC, ranlavanet approved these changes

2023-05-08 12:21 UTC, merged